# Generated by Django 6.0.1 on 2026-05-05 14:17

import django.db.models.deletion
import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.CharField(default=utils.utils.generate_ids, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.CharField(default=utils.utils.generate_ids, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.CharField(default=utils.utils.generate_ids, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='Contacts.district')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='Contacts.province'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.CharField(default=utils.utils.generate_ids, max_length=64, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(max_length=64)),
                ('ward_number', models.CharField(max_length=10)),
                ('tole', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='Organizations.organization')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contacts.district')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contacts.municipality')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contacts.province')),
            ],
        ),
    ]
