# Generated by Django 6.0.1 on 2026-05-05 14:17

import django.db.models.deletion
import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(default=utils.utils.generate_ids, max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('event_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.CharField(default=utils.utils.generate_ids, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('abbr', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.CharField(default=utils.utils.generate_ids, max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='Organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Image',
            fields=[
                ('id', models.CharField(default=utils.utils.generate_ids, max_length=64, primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Organizations.event')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_images', to='Organizations.organization')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='Organizations.organization'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.CharField(default=utils.utils.generate_ids, max_length=64, primary_key=True, serialize=False)),
                ('file_url', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Academic_Year',
            fields=[
                ('id', models.CharField(default=utils.utils.generate_ids, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='Organizations.organization')),
            ],
        ),
    ]
