# Generated by Django 6.0.1 on 2026-05-05 14:17

import django.db.models.deletion
import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employees', '0001_initial'),
        ('Organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.CharField(default=utils.utils.generate_ids, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('section', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizations.academic_year')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.CharField(default=utils.utils.generate_ids, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizations.academic_year')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academics.class')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizations.organization')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.teacher')),
            ],
        ),
    ]
